# Generated by Django 4.2.5 on 2023-11-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_receipt_atm_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transfer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('recipient_iban', models.CharField(max_length=23)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipientIBAN',
        ),
        migrations.AddField(
            model_name='transaction',
            name='content',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.AddField(
            model_name='transfer',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
    ]
