# Generated by Django 4.2.5 on 2023-11-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('IBAN', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='HolderType',
            fields=[
                ('holderType_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.atmuser')),
            ],
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.bankaccount')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.holdertype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.atmuser')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='holders',
            field=models.ManyToManyField(through='user.Holder', to='user.atmuser'),
        ),
    ]
