# Generated by Django 4.2.5 on 2023-11-13 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMMachine',
            fields=[
                ('atm_machine_uid', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('current_balance', models.BigIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('minimum_balance', models.BigIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('managed_machines', models.ManyToManyField(to='admininstrator.atmmachine')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
