@startuml UserCaseATM
class ATM {
    -id : int 
    -location : String
    +performTransaction()
}
class ATMAdmin {
    -admin_id : int
    -username : String
    -password : String
    +manageATM()
    +monitorTransactions()
}

class Client {
    -id : int
    -frist_name : String
    -last_name : String
    -email : String
    -phone_number : String
    -address : String
    +initiateTransaction()
    +authenticate()
}

class BankAccount { 
    -idBankAccount : int
    -idTransaction : int
    -IBAN : String
    -Balance : float 
}

class Transaction {
    -idTransaction : int
    -type : String
    -timestamp : String
    -amount : float
    +processTransaction()
}

class TypeTransacao {
    -idType : int 
    -name : String
    +execute()    
}

class Receipt {
    -receipt_id : int
    -content : String
}

ATM -- Client : interacts
ATM -- ATMAdmin : managed by
Client -- Transaction : initiates 
Transaction -- TransactionType : has
Transaction -- Receipt : generates
TransactionType -- ATM : executes
@enduml