# Generated by Django 4.2.5 on 2023-11-13 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('transaction', '0002_alter_transaction_recipientiban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='account',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='transaction.transactiontype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.transactiontype'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.bankaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_types',
            field=models.ManyToManyField(to='transaction.transactiontype'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transaction',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transaction_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='transaction.transactiontype'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
