# Generated by Django 4.2.5 on 2023-11-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_user_id_receipt_user_remove_deposit_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='atm_location',
        ),
    ]
